services:
  php:
    build:
      dockerfile: Dockerfile.dev
    container_name: interview-tintint-php
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: interview-tintint-nginx
    ports:
      - 8000:80
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
